export enum AuditAction {
  // Auth actions
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  SIGNUP = 'SIGNUP',
  PASSWORD_RESET_REQUEST = 'PASSWORD_RESET_REQUEST',
  PASSWORD_RESET_COMPLETE = 'PASSWORD_RESET_COMPLETE',
  FAILED_LOGIN = 'FAILED_LOGIN',

  // Transaction actions
  DEPOSIT_CREATED = 'DEPOSIT_CREATED',
  WITHDRAWAL_CREATED = 'WITHDRAWAL_CREATED',
  SWAP_CREATED = 'SWAP_CREATED',
  TRANSACTION_STATUS_UPDATED = 'TRANSACTION_STATUS_UPDATED',
  TRANSACTION_CANCELLED = 'TRANSACTION_CANCELLED',
  TRANSACTION_CREATED = 'TRANSACTION_CREATED',
  TRANSACTION_CREATED_FAILED = 'TRANSACTION_CREATED_FAILED',
  TRANSACTION_SIGNED = 'TRANSACTION_SIGNED',
  TRANSACTION_SUBMITTED = 'TRANSACTION_SUBMITTED',
  TRANSACTION_VERIFIED = 'TRANSACTION_VERIFIED',

  // Wallet actions
  WALLET_CREATED = 'WALLET_CREATED',
  WALLET_KEY_GENERATED = 'WALLET_KEY_GENERATED',
  WALLET_BALANCE_UPDATED = 'WALLET_BALANCE_UPDATED',

  // System actions
  SCHEDULED_JOB_STARTED = 'SCHEDULED_JOB_STARTED',
  SCHEDULED_JOB_COMPLETED = 'SCHEDULED_JOB_COMPLETED',
  SCHEDULED_JOB_FAILED = 'SCHEDULED_JOB_FAILED',
  EXCHANGE_RATE_UPDATED = 'EXCHANGE_RATE_UPDATED',
  SYSTEM_BACKUP = 'SYSTEM_BACKUP',
  SYSTEM_CHECK = 'SYSTEM_CHECK',
  RATE_ALERT_TRIGGERED = 'RATE_ALERT_TRIGGERED',

  // Fee actions
  FEE_CONFIG_CREATED = 'FEE_CONFIG_CREATED',
  FEE_CONFIG_UPDATED = 'FEE_CONFIG_UPDATED',

  // Admin actions
  USER_UPDATED = 'USER_UPDATED',
  USER_DELETED = 'USER_DELETED',
  ADMIN_LOGIN = 'ADMIN_LOGIN',
  ADMIN_ACCOUNT_CREATED = 'ADMIN_ACCOUNT_CREATED',
  ROLE_CHANGE = 'ROLE_CHANGE',
  PLAN_CHANGE = 'PLAN_CHANGE',
  USER_SUSPENDED = 'USER_SUSPENDED',
  USER_UNSUSPENDED = 'USER_UNSUSPENDED',
  PLATFORM_CONFIG_UPDATED = 'PLATFORM_CONFIG_UPDATED',
  SUPER_ADMIN_AUDIT_LOGS_VIEWED = 'SUPER_ADMIN_AUDIT_LOGS_VIEWED',

  // Data export / deletion actions
  DATA_EXPORT_REQUESTED = 'DATA_EXPORT_REQUESTED',
  DATA_EXPORT_PROCESSED = 'DATA_EXPORT_PROCESSED',
  DATA_EXPORT_CANCELLED = 'DATA_EXPORT_CANCELLED',
  ACCOUNT_DELETION_REQUESTED = 'ACCOUNT_DELETION_REQUESTED',
  ACCOUNT_DELETION_COMPLETED = 'ACCOUNT_DELETION_COMPLETED',
}
